"""
agents/judge_agent.py
---------------------
Judge Agent: Evaluates multiple candidate patches generated by parallel coding agents,
selects the best one based on correctness and simplicity, and applies it to the disk.

Output written to state:
  - patch          (the winning candidate's patch/description)
  - modified_files (the winning candidate's modified files)
  - judge_reasoning (why the judge picked this candidate)
  - candidates     (cleared for next run)
"""

import os
import re
import logging
from pathlib import Path

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from dotenv import load_dotenv

from state import AgentState, Candidate

load_dotenv()
logger = logging.getLogger(__name__)


def _get_llm() -> ChatGroq:
    api_key = os.getenv("GROQ_API_KEY")
    model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
    return ChatGroq(api_key=api_key, model=model, temperature=0.1)


def _apply_winning_candidate(candidate: Candidate, repo_dir: str) -> list[str]:
    """Writes the parsed files from the winning candidate to disk."""
    modified_files: list[str] = []
    
    for rel_path, code in candidate["parsed_files"].items():
        full_path = Path(repo_dir) / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(code, encoding="utf-8")
        modified_files.append(rel_path)
        logger.info(f"  ✔ Applied winning fix to: {rel_path}")
        
    return modified_files


def run_judge_agent(state: AgentState) -> AgentState:
    """
    LangGraph node function for the Judge Agent.
    
    Reads: issue_title, issue_body, analysis, candidates, repo_dir
    Writes: patch, modified_files, judge_reasoning, candidates (cleared)
    """
    logger.info("══════════  JUDGE AGENT  ══════════")
    
    candidates = state.get("candidates", [])
    if not candidates:
        logger.warning("Judge received no candidates to evaluate!")
        return state
        
    # If there's only one candidate (e.g. one failed or during testing), just pick it
    if len(candidates) == 1:
        logger.info("Only 1 candidate generated. Selecting by default.")
        winner = candidates[0]
        modified_files = _apply_winning_candidate(winner, state["repo_dir"])
        return {
            **state,
            "patch": winner["patch"],
            "modified_files": modified_files,
            "judge_reasoning": "Only one candidate was generated.",
            "candidates": [] # Clear for potential retries
        }

    issue_title = state.get("issue_title", "Unknown")
    issue_body = state.get("issue_body", "")
    analysis = state.get("analysis", "")
    
    logger.info(f"Evaluating {len(candidates)} candidates...")
    
    # ── Build Candidate Context ───────────────────────────────────────────
    candidates_text = ""
    for i, candidate in enumerate(candidates):
        candidates_text += f"\n\n### CANDIDATE {i + 1} ({candidate['agent_name']})\n"
        candidates_text += f"```python\n{candidate['patch']}\n```\n"

    # ── Build Evaluation Prompt ───────────────────────────────────────────
    system_prompt = """You are a Senior Staff Engineer acting as a code judge.
Your task is to evaluate multiple candidate code fixes for a given issue and select the best one.

EVALUATION CRITERIA:
1. Correctness: Does it solve the root cause?
2. Simplicity: Is it elegant and minimal?
3. Safety: Does it avoid breaking other functionality?

CRITICAL INSTRUCTIONS:
- You must select exactly ONE winning candidate.
- Output your step-by-step reasoning first.
- End your response with exactly: CHOICE: <Candidate Number>
  (For example: CHOICE: 1 or CHOICE: 2)
"""

    user_prompt = f"""## Issue: {issue_title}
{issue_body}

## Root Cause Analysis
{analysis}

## Candidates
{candidates_text}

Evaluate the candidates and make your final selection using the format: CHOICE: <number>.
"""

    llm = _get_llm()
    logger.info("Calling Groq to judge candidates...")
    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt),
    ])
    
    raw_output = response.content
    logger.info("Judging complete.")
    
    # ── Parse Selection ───────────────────────────────────────────────────
    winner_idx = 0 # Default to first if parsing fails
    match = re.search(r"CHOICE:\s*(\d+)", raw_output)
    if match:
        try:
            choice = int(match.group(1)) - 1
            if 0 <= choice < len(candidates):
                winner_idx = choice
                logger.info(f"Judge selected Candidate {choice + 1} ({candidates[choice]['agent_name']})")
            else:
                logger.warning(f"Judge returned invalid choice index: {choice}. Defaulting to 1.")
        except ValueError:
            logger.warning("Failed to parse judge choice. Defaulting to 1.")
    else:
        logger.warning("Judge did not output CHOICE: format. Defaulting to 1.")

    winner = candidates[winner_idx]
    
    # ── Apply Winning Patch ────────────────────────────────────────────────
    modified_files = _apply_winning_candidate(winner, state["repo_dir"])
    
    return {
        **state,
        "patch": winner["patch"],
        "modified_files": modified_files,
        "judge_reasoning": raw_output,
        "candidates": [], # Clear for potential next attempt
    }
