"""
agents/pr_agent.py
------------------
PR Agent: Creates a Git branch, commits the modified files and generated tests,
pushes to GitHub, and opens a Pull Request with an LLM-generated description.

Output written to state:
  - branch_name  (new branch created)
  - pr_url       (URL of the opened PR)
"""

import os
import re
import logging
from pathlib import Path

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from dotenv import load_dotenv

from state import AgentState
from utils.github_client import create_branch, push_changes, create_pull_request

load_dotenv()
logger = logging.getLogger(__name__)

TEST_FILE_NAME = "test_ai_generated.py"


def _get_llm() -> ChatGroq:
    api_key = os.getenv("GROQ_API_KEY")
    model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
    return ChatGroq(api_key=api_key, model=model, temperature=0.3)


def _slugify(text: str, max_len: int = 40) -> str:
    """Convert issue title to a URL-safe slug."""
    slug = re.sub(r"[^a-zA-Z0-9\s-]", "", text.lower())
    slug = re.sub(r"\s+", "-", slug.strip())
    return slug[:max_len].rstrip("-")


def run_pr_agent(state: AgentState) -> AgentState:
    """
    LangGraph node function for the PR Agent.

    Reads:  repo_url, repo_dir, issue_number, issue_title, issue_body,
            analysis, patch, modified_files, test_results
    Writes: branch_name, pr_url
    """
    logger.info("══════════  PR AGENT  ══════════")

    repo_url = state["repo_url"]
    repo_dir = state["repo_dir"]
    issue_number = state["issue_number"]
    github_token = state["github_token"]
    issue_title = state.get("issue_title", f"issue-{issue_number}")
    analysis = state.get("analysis", "")
    patch = state.get("patch", "")
    modified_files = state.get("modified_files", [])
    test_results = state.get("test_results", "")

    # ── Generate branch name ───────────────────────────────────────────────
    slug = _slugify(issue_title)
    branch_name = f"fix/issue-{issue_number}-{slug}"
    logger.info(f"Branch name: {branch_name}")

    # ── Create and checkout branch ─────────────────────────────────────────
    create_branch(repo_dir, branch_name)

    # ── Collect all files to commit ────────────────────────────────────────
    files_to_commit = list(modified_files)
    test_file_path = Path(repo_dir) / TEST_FILE_NAME
    if test_file_path.exists():
        files_to_commit.append(TEST_FILE_NAME)

    # Remove any duplicates and non-existent paths
    files_to_commit = list(dict.fromkeys(
        f for f in files_to_commit
        if (Path(repo_dir) / f).exists()
    ))

    if not files_to_commit:
        logger.warning(
            "No files to commit — the coding agent may not have modified anything."
        )
        return {
            **state,
            "branch_name": branch_name,
            "pr_url": "",
            "error": "PR Agent: no modified files to commit.",
        }

    logger.info(f"Committing files: {files_to_commit}")

    # ── Generate PR title and description with Groq ────────────────────────
    system_prompt = """You are a senior developer writing a GitHub Pull Request.
Write a professional, informative PR title and body in Markdown.

Format your response as:
TITLE: <concise PR title, max 72 chars>

BODY:
<markdown body>"""

    user_prompt = f"""## Issue #{issue_number}: {issue_title}

{state.get('issue_body', '')}

## Root Cause Analysis
{analysis[:1500]}

## Changes Made
{patch[:1500]}

## Test Results
```
{test_results[:800]}
```

Write a clear PR title and description for these changes."""

    llm = _get_llm()
    logger.info("Generating PR description with Groq …")
    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt),
    ])
    raw = response.content

    # Parse TITLE and BODY
    title_match = re.search(r"TITLE:\s*(.+)", raw)
    body_match = re.search(r"BODY:\s*(.*)", raw, re.DOTALL)

    pr_title = title_match.group(1).strip() if title_match else f"fix: resolve issue #{issue_number}"
    pr_body = body_match.group(1).strip() if body_match else raw

    # Add standard footer
    pr_body += f"""

---
*This PR was automatically generated by the AI Orchestration System.*
*Closes #{issue_number}*"""

    # ── Push changes to GitHub ─────────────────────────────────────────────
    commit_message = f"fix(#{issue_number}): {issue_title[:60]}"
    logger.info("Pushing changes …")
    push_changes(repo_dir, branch_name, files_to_commit, github_token, commit_message)

    # ── Open Pull Request ──────────────────────────────────────────────────
    logger.info("Opening Pull Request …")
    pr_url = create_pull_request(
        repo_url=repo_url,
        branch_name=branch_name,
        title=pr_title,
        body=pr_body,
        github_token=github_token,
    )

    logger.info(f"✅ PR created: {pr_url}")

    return {
        **state,
        "branch_name": branch_name,
        "pr_url": pr_url,
    }
